ppw2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web2.urls')),
]

web2/urls.py
from django.urls import path
from .views import create_status

app_name = 'status'

urlpatterns = [
    path('', create_status, name='status'),
]

web2/models.py
from django.db import models

# Create your models here.

class Status(models.Model):
    status = models.CharField(max_length=300)

    def __str__(self):
        return self.status

web2/forms.py
from django import forms
from . import models

class Status_Form(forms.ModelForm):
    class Meta:
        model = models.Status
        fields = ['status']
        widget = {'status': forms.CharField(label=None)}

web2/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import forms

# Create your views here.

def create_status(request):
    if request.method == "POST":
        form = forms.Status_Form(request.POST)
        if form.is_valid():
            #saving form to db
            form.save()

            form = forms.Status_Form()
            context = {'form':form}
            return render(request, 'home.html', context)

    else:
        form = forms.Status_Form()
        context = {'form':form}
        return render(request, 'home.html', context)

web2/templates/home.html
{% load static %}

<html>
    <head>
        <title>New Page</title>
        <link rel="stylesheet" href= "{% static 'style.css' %}">
    </head>
    <body>

        <div class="text-hello">
            <h1>Hello, Apa kabar?</h1>
        </div>
        <div class="form">
            <form action="{% url 'status:status'  %}" method="POST">
            {% csrf_token %}
            {{ form }}
                <input type="submit" value="Send">
            </form>
        </div>
    </body>
</html>